# Generated by Django 2.1.8 on 2019-05-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePaciente', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField()),
                ('especialista', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'cita',
                'verbose_name_plural': 'citas',
            },
        ),
    ]
