# Generated by Django 2.1.8 on 2019-05-17 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
