# Generated by Django 2.1.8 on 2019-05-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0007_auto_20190517_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
