# Generated by Django 2.1.8 on 2019-05-18 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0008_auto_20190517_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='paciente',
        ),
    ]
