# Generated by Django 2.1.8 on 2019-05-18 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0010_paciente_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='paciente',
        ),
    ]
